server:
  port: 8899
  error:
    path: /error
spring:
  profiles:
    active: prod
    include:
      - druid
      - mybatis
      - redis
      - thread-pool
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: ${SQLITE_URL:jdbc:sqlite:file:./attachments/db/windy-crypto.sqlite}
    username:
    password:
    type: com.alibaba.druid.pool.DruidDataSource
  messages:
    basename: messages # i18n messages 国际化,src/main/resources/messages.properties
    encoding: utf-8
  main:
    banner-mode: off
logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml # 指定哪个日志配置文件才生效
  level:
    org.mybatis: ${IBATIS_LOG_LEVEL:WARN}
    org.apache.ibatis: ${IBATIS_LOG_LEVEL:WARN}