spring:
  datasource:
    druid:
      initialSize: 2  # 初始连接数
      minIdle: 5  # 最小连接池数量
      maxActive: 10  # 最大连接池数量
      maxWait: 10000  # 获取连接等待超时时间
      connectTimeout: 10000  # 连接超时时间
      socketTimeout: 1000  # 网络超时时间
      timeBetweenEvictionRunsMillis: 60000  # 检测空闲连接的时间间隔
      minEvictableIdleTimeMillis: 300000  # 连接在池中最小生存时间
      maxEvictableIdleTimeMillis: 900000  # 连接在池中最大生存时间
      validationQuery: SELECT count(1) FROM "sys_config"  # 验证连接是否有效的查询语句,视数据库而定,例如MySQL为SELECT 1
      testWhileIdle: true  # 检测空闲连接时是否执行验证
      testOnBorrow: false  # 检测从连接池借出连接时是否执行验证
      testOnReturn: false  # 检测返回连接到连接池时是否执行验证
      webStatFilter: # WebStatFilter配置
        enabled: true  # 是否启用WebStatFilter
      statViewServlet: # StatViewServlet配置
        enabled: true  # 是否启用StatViewServlet
        allow:  # 白名单配置
        url-pattern: /druid/*  # URL匹配模式
        login-username: dororo  # 控制台管理用户名
        login-password: dororo  # 控制台管理密码
      filter: # 过滤器配置
        stat: # StatFilter配置
          enabled: true  # 是否启用StatFilter
          log-slow-sql: true  # 是否记录慢SQL
          slow-sql-millis: 1000  # 慢SQL的时间阈值
          merge-sql: true  # 是否合并SQL
        wall: # WallFilter配置
          config:
            multi-statement-allow: true  # 允许多语句执行