windy-thread-pool:
  dispatcher:
    core-pool-size: 500
    max-pool-size: 1000
    queue-capacity: 500
    keep-alive-seconds: 60
  crypto:
    core-pool-size: 18
    max-pool-size: 24
    queue-capacity: 20000
    keep-alive-seconds: 60
  stat:
    core-pool-size: 12
    max-pool-size: 16
    queue-capacity: 500
    keep-alive-seconds: 60