; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "${fmMyAppName}"
#define MyAppVersion "1.0"
#define MyAppPublisher "${fmMyAppPublisher}"
#define MyAppExeName "startup.bat"
#define MyJreDirName "jre"
#define MyAttachmentsDirName "attachments"
#define MyConfigDirName "config"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId=${r'{{'}${fmAppId}${r'}'}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={pf}\{#MyAppName}
DisableProgramGroupPage=yes
InfoAfterFile=${fmInfoAfterFile}
OutputDir=D:\gust\dev\project\github\windy-crypto\target\exe-exe2setup
OutputBaseFilename=${fmOutputBaseFilename}
SetupIconFile=${fmSetupIconFile}
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "${fmStartupBatPath}"; DestDir: "{app}"; Flags: ignoreversion
Source: "${fmJar2exePath}"; DestDir: "{app}"; Flags: ignoreversion
Source: "${fmAttachmentsPath}\*"; DestDir: "{app}\{#MyAttachmentsDirName}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "${fmConfigPath}\*"; DestDir: "{app}\{#MyConfigDirName}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "${fmJreDirPath}\*"; DestDir: "{app}\{#MyJreDirName}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{commonprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: shellexec postinstall skipifsilent

