; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "windy-crypto"
#define MyAppVersion "1.0"
#define MyAppPublisher "Windy"
#define MyAppExeName "startup.bat"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{45AAA6A8-F6F3-4A0C-B33C-E967E9B910FF}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={pf}\{#MyAppName}
DisableProgramGroupPage=yes
InfoAfterFile=D:\gust\dev\project\github\windy-crypto\target\infoFileAfterInstall.txt
OutputDir=D:\gust\dev\project\github\windy-crypto\target\exe-exe2setup
OutputBaseFilename=windy-crypto-setup
SetupIconFile=D:\gust\dev\project\github\windy-crypto\target\0002.ico
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "D:\gust\dev\project\github\windy-crypto\target\startup.bat"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\gust\dev\project\github\windy-crypto\target\startup.bat"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\gust\dev\project\github\windy-crypto\target\exe-jar2exe\windy-crypto.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\gust\dev\project\github\windy-crypto\target\attachments\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\gust\dev\project\github\windy-crypto\target\config\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{commonprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: shellexec postinstall skipifsilent

